version: '3.8'

services:

  # MLflow Tracking Server
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: >
      mlflow server
      --backend-store-uri /app/mlruns
      --default-artifact-root s3://your-mlflow-bucket/artifacts
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}

  # Prefect Server
  prefect-server:
    image: prefecthq/prefect:2-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"

  # Prefect Worker
  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    command: prefect worker start --pool default-agent-pool
    depends_on:
      - prefect-server
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns

  # Air Pollution API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - USE_S3=${USE_S3:-false}
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns

  # Streamlit Dashboard
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://localhost:8000/api/v1


